import com.vereview.MainApp;
import org.apache.commons.lang3.exception.ExceptionUtils;
import org.junit.Assert;
import org.junit.Test;

public class MainAppTest extends Assert {

    /*
    @Test
    public void mainTest() {
        try {
            String[] args = new String[]{"dbName=case_12_3233", "exportDir=\\\\192.168.0.110\\data", "env=DEV"};
            MainApp.main(args);
        } catch (Throwable t) {
            fail(ExceptionUtils.getStackTrace(t));
        }
    }

     */

}
